name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install Dependencies
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Windows" ]] ; then
          export VCPKG_DEFAULT_TRIPLET=x64-windows-static
          export VCPKG_LIBRARY_LINKAGE=static
          vcpkg install pixman freetype harfbuzz zlib
        elif [[ "${{ runner.os }}" == "macOS" ]] ; then
          brew install pixman freetype harfbuzz zlib
        else
          sudo apt-get update -qq
          sudo apt-get install -y \
            libpixman-1-dev libfreetype6-dev libharfbuzz-dev zlib1g-dev \
            libx11-dev libxcursor-dev libxi-dev
        fi
    - uses: ilammy/msvc-dev-cmd@v1
      if: runner.os == 'Windows'
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Generating Makefiles
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Windows" ]] ; then
          cmake . -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake \
            -DVCPKG_TARGET_TRIPLET=x64-windows-static
        else
          cmake . -G Ninja
        fi
    - name: Compiling
      shell: bash
      run: |
        ninja
    - name: Running Tests
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Linux" ]] ; then
          export XVFB=xvfb-run
        fi
        $XVFB ctest --output-on-failure
