name: Post Clang Tidy Comments
on:
  workflow_run:
    workflows: ["Clang Tidy Diff"]
    types:
    - completed

permissions:
  checks: write
  pull-requests: write

jobs:
  post-comments:
    runs-on: ubuntu-latest
    steps:
    - uses: ZedThree/clang-tidy-review/post@9a32adc734e10e4d84baa60f2b7d7c021568c527
      with:
        token: ${{ secrets.CLANG_TIDY_TOKEN }}
